{"name": "Negative Test for Employee Attributes", "status": "failed", "statusDetails": {"message": "AssertionError: [Desired user's attrs are equal to desired dict of attrs] Expected <{.., 'team_size': 5}> to be equal to <{.., 'team_size': 7}>, but was not.", "trace": "self = <Lesson_30.test_employee.TestEmployee object at 0x105bfb530>\n\n    @allure.story('Test Allure')\n    @allure.title('Negative Test for Employee Attributes')\n    def test_employee_attrs_negative(self):\n        logger.info(\"Starting negative test for employee attributes\")\n    \n        logger.info(f\"Expected attributes: {self.failed_mark_attrs}\")\n        logger.info(f\"Actual attributes: {self.qa_automation_team_lead.__dict__}\")\n    \n        logger.info(\"Comparing actual attributes with expected attributes\")\n        assert_that(self.qa_automation_team_lead.__dict__,\n>                   \"Desired user's attrs are equal to desired dict of attrs\").is_equal_to(self.failed_mark_attrs)\nE       AssertionError: [Desired user's attrs are equal to desired dict of attrs] Expected <{.., 'team_size': 5}> to be equal to <{.., 'team_size': 7}>, but was not.\n\ntest_employee.py:51: AssertionError"}, "start": 1730379910208, "stop": 1730379910208, "uuid": "921cb18a-e0ab-4bac-a2bf-bcd2b4556182", "historyId": "bdb622a7ceef6a74cb7b3b4ff0bc43ce", "testCaseId": "bdb622a7ceef6a74cb7b3b4ff0bc43ce", "fullName": "test_employee.TestEmployee#test_employee_attrs_negative", "labels": [{"name": "story", "value": "Test Allure"}, {"name": "suite", "value": "test_employee"}, {"name": "subSuite", "value": "TestEmployee"}, {"name": "host", "value": "Air-Sergij"}, {"name": "thread", "value": "95497-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_employee"}]}